name: Scala CI - Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests	
      run: sbt test
    - name: Setup GPG for signing artifacts
      env:
        GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        GPG_TTY: $(tty)
      run: |
        mkdir -p ~/.gnupg/
        printf "$GPG_SECRET_KEY" | base64 --decode > ~/.gnupg/private.key
        gpg --import ~/.gnupg/private.key
    - name: Create local staging bundle (signed)
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: sbt publishSigned
    - name: Bundle release to Sonatype
      env:
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PWD: ${{ secrets.SONATYPE_PWD}}
      run: sbt sonatypeBundleRelease
